In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("WorldCups.csv")

In [3]:
df.head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607

In [4]:
df = df.dropna(how="all")

In [5]:
df = df.drop_duplicates()

In [6]:
text_cols = df.select_dtypes(include="object").columns
df[text_cols] = df[text_cols].apply(lambda col: col.str.strip())

In [7]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

In [8]:
df.columns

Index(['year', 'country', 'winner', 'runners-up', 'third', 'fourth',
       'goalsscored', 'qualifiedteams', 'matchesplayed', 'attendance'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            20 non-null     int64
 1   country         20 non-null     object
 2   winner          20 non-null     object
 3   runners-up      20 non-null     object
 4   third           20 non-null     object
 5   fourth          20 non-null     object
 6   goalsscored     20 non-null     int64
 7   qualifiedteams  20 non-null     int64
 8   matchesplayed   20 non-null     int64
 9   attendance      20 non-null     object
dtypes: int64(4), object(6)
memory usage: 1.7+ KB

In [10]:
df.isnull().sum()

year              0
country           0
winner            0
runners-up        0
third             0
fourth            0
goalsscored       0
qualifiedteams    0
matchesplayed     0
attendance        0
dtype: int64

In [11]:
df.head()

,year,country,winner,runners-up,third,fourth,goalsscored,qualifiedteams,matchesplayed,attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607

In [12]:
df.to_csv("WorldCups_cleaned.csv", index=False)